version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/app
  
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 5004:80
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
